server:
  port: 8080
#  context-path: /base
spring:
  application:
   name: eval
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: LEGACYHTML5
  redis:
    database: 0
    timeout: 3000ms
    host: 192.168.1.87
    port: 6379
    password: huajie
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000ms
  #      cluster:
  #        max-redirects: 10
  #        nodes: 127.0.0.1:6080
mybatis:
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*/*.xml
